# Generated by Django 3.0.7 on 2020-07-27 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyuser',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', related_query_name='recently_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recentlyuser',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', related_query_name='recently_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
