# Generated by Django 3.0.7 on 2020-07-14 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_user_relations_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relations_users',
            field=models.ManyToManyField(related_name='_user_relations_users_+', through='members.Relations', to=settings.AUTH_USER_MODEL),
        ),
    ]
