# Generated by Django 3.0.7 on 2020-07-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200706_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='introduce',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
