# Generated by Django 3.0.7 on 2020-07-20 07:37

from django.db import migrations, models
import django.db.models.deletion
import stories.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(null=True, upload_to=stories.models.story_image),
        ),
        migrations.AlterField(
            model_name='storycheck',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_set', to='stories.Story'),
        ),
        migrations.DeleteModel(
            name='StoryImage',
        ),
    ]
